/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeatsRouteImport } from './routes/seats'
import { Route as SuccessRouteImport } from './routes/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsRoute = SeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/passenger': typeof PassengerRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/passenger': typeof PassengerRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/passenger': typeof PassengerRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/success': typeof SuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/login'
    | '/passenger'
    | '/payment'
    | '/search'
    | '/seats'
    | '/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/login'
    | '/passenger'
    | '/payment'
    | '/search'
    | '/seats'
    | '/success'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/login'
    | '/passenger'
    | '/payment'
    | '/search'
    | '/seats'
    | '/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  PassengerRoute: typeof PassengerRoute
  PaymentRoute: typeof PaymentRoute
  SearchRoute: typeof SearchRoute
  SeatsRoute: typeof SeatsRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats': {
      id: '/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  PassengerRoute: PassengerRoute,
  PaymentRoute: PaymentRoute,
  SearchRoute: SearchRoute,
  SeatsRoute: SeatsRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
